name: Conventional Commits and PR Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  commit-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  pr-linting:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          validateSingleCommit: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
