name: Conventional Commits

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  commit-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
